# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8b903c825176a5313eb1e15c192969d150654a01cf027a6ee5efdca311d4e8f031dc8119f2c5c8a3b88ce9e946e38a40f1ca12b622bb5f637be62951e89139

test:
  secret_key_base: 41626d8eef2427bf4bbb9af6ae61e2a2d165b8123131c05b0f4ec135c964cf6ac0ff7bb2bcce8437059bd626fc13f10a718e060b04be0338981bedad78162344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
